services:
  backend:
    build:
      context: ./src/ml
      dockerfile: Dockerfile
    container_name: mnist-backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./dataset:/app/dataset

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: mnist-frontend
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    depends_on:
      - backend
